{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 3,
      "id": "0bb2924e-12fa-4202-957b-b5da331b8bb8",
      "metadata": {
        "id": "3f2dd43f4adf"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: google-cloud-aiplatform in /home/jupyter/.local/lib/python3.7/site-packages (1.20.0)\n",
            "Requirement already satisfied: google-cloud-bigquery in /opt/conda/lib/python3.7/site-packages (2.34.4)\n",
            "Collecting google-cloud-bigquery\n",
            "  Using cached google_cloud_bigquery-3.4.1-py2.py3-none-any.whl (215 kB)\n",
            "Collecting google-api-core==2.10\n",
            "  Using cached google_api_core-2.10.0-py3-none-any.whl (115 kB)\n",
            "Collecting protobuf<5.0.0dev,>=3.20.1\n",
            "  Downloading protobuf-4.21.12-cp37-abi3-manylinux2014_x86_64.whl (409 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m409.8/409.8 kB\u001b[0m \u001b[31m8.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: requests<3.0.0dev,>=2.18.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core==2.10) (2.28.1)\n",
            "Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core==2.10) (2.15.0)\n",
            "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /home/jupyter/.local/lib/python3.7/site-packages (from google-api-core==2.10) (1.56.4)\n",
            "Requirement already satisfied: google-cloud-storage<3.0.0dev,>=1.32.0 in /home/jupyter/.local/lib/python3.7/site-packages (from google-cloud-aiplatform) (1.44.0)\n",
            "Requirement already satisfied: google-cloud-resource-manager<3.0.0dev,>=1.3.3 in /opt/conda/lib/python3.7/site-packages (from google-cloud-aiplatform) (1.6.0)\n",
            "Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0 in /opt/conda/lib/python3.7/site-packages (from google-cloud-aiplatform) (2.11.0)\n",
            "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.0 in /home/jupyter/.local/lib/python3.7/site-packages (from google-cloud-aiplatform) (1.22.1)\n",
            "Requirement already satisfied: packaging<22.0.0dev,>=14.3 in /opt/conda/lib/python3.7/site-packages (from google-cloud-aiplatform) (21.3)\n",
            "Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from google-cloud-bigquery) (1.3.3)\n",
            "Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /opt/conda/lib/python3.7/site-packages (from google-cloud-bigquery) (2.8.2)\n",
            "  Using cached protobuf-3.20.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)\n",
            "Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.4.1 in /opt/conda/lib/python3.7/site-packages (from google-cloud-bigquery) (2.3.2)\n",
            "Requirement already satisfied: grpcio<2.0dev,>=1.38.1 in /home/jupyter/.local/lib/python3.7/site-packages (from google-cloud-bigquery) (1.50.0)\n",
            "Collecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0\n",
            "  Using cached google_api_core-2.11.0-py3-none-any.whl (120 kB)\n",
            "  Using cached google_api_core-2.10.2-py3-none-any.whl (115 kB)\n",
            "  Using cached google_api_core-2.10.1-py3-none-any.whl (115 kB)\n",
            "Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in /home/jupyter/.local/lib/python3.7/site-packages (from google-api-core==2.10) (1.34.1)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core==2.10) (0.2.7)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core==2.10) (4.9)\n",
            "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/jupyter/.local/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core==2.10) (4.2.4)\n",
            "Requirement already satisfied: six>=1.9.0 in /home/jupyter/.local/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core==2.10) (1.15.0)\n",
            "Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in /opt/conda/lib/python3.7/site-packages (from google-cloud-resource-manager<3.0.0dev,>=1.3.3->google-cloud-aiplatform) (0.12.4)\n",
            "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /opt/conda/lib/python3.7/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery) (1.1.2)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/jupyter/.local/lib/python3.7/site-packages (from packaging<22.0.0dev,>=14.3->google-cloud-aiplatform) (2.4.7)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.10) (3.3)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.10) (1.26.11)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.10) (2022.9.14)\n",
            "Requirement already satisfied: charset-normalizer<3,>=2 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core==2.10) (2.1.0)\n",
            "Requirement already satisfied: cffi>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery) (1.15.1)\n",
            "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-api-core==2.10) (0.4.8)\n",
            "Requirement already satisfied: pycparser in /opt/conda/lib/python3.7/site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery) (2.21)\n",
            "Installing collected packages: protobuf, google-api-core\n",
            "  Attempting uninstall: protobuf\n",
            "    Found existing installation: protobuf 3.19.6\n",
            "    Uninstalling protobuf-3.19.6:\n",
            "      Successfully uninstalled protobuf-3.19.6\n",
            "  Attempting uninstall: google-api-core\n",
            "    Found existing installation: google-api-core 2.11.0\n",
            "    Uninstalling google-api-core-2.11.0:\n",
            "      Successfully uninstalled google-api-core-2.11.0\n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires absl-py<0.13,>=0.9, but you have absl-py 1.3.0 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires google-cloud-bigquery<2.21,>=1.28.0, but you have google-cloud-bigquery 2.34.4 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires numpy<1.20,>=1.16, but you have numpy 1.21.6 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<2.6,>=1.15.2, but you have tensorflow 2.11.0 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires tensorflow-metadata<1.3.0,>=1.2.0, but you have tensorflow-metadata 1.12.0 which is incompatible.\n",
            "tensorflow-io 0.18.0 requires tensorflow<2.6.0,>=2.5.0, but you have tensorflow 2.11.0 which is incompatible.\n",
            "tensorflow-io 0.18.0 requires tensorflow-io-gcs-filesystem==0.18.0, but you have tensorflow-io-gcs-filesystem 0.27.0 which is incompatible.\n",
            "tensorflow-docs 0.0.0.dev0 requires protobuf<3.20,>=3.12.0, but you have protobuf 3.20.3 which is incompatible.\n",
            "kfp 1.8.14 requires google-auth<2,>=1.6.1, but you have google-auth 2.15.0 which is incompatible.\n",
            "google-vizier 0.0.4 requires absl-py<1.0,>=0.7, but you have absl-py 1.3.0 which is incompatible.\n",
            "google-vizier 0.0.4 requires googleapis-common-protos==1.56.0, but you have googleapis-common-protos 1.56.4 which is incompatible.\n",
            "google-vizier 0.0.4 requires grpcio<=1.47.0,>=1.35.0, but you have grpcio 1.50.0 which is incompatible.\n",
            "google-vizier 0.0.4 requires numpy==1.21.5, but you have numpy 1.21.6 which is incompatible.\n",
            "google-cloud-recommendations-ai 0.2.0 requires google-api-core[grpc]<2.0.0dev,>=1.22.2, but you have google-api-core 2.10.0 which is incompatible.\n",
            "google-cloud-pubsub 2.6.0 requires google-api-core[grpc]<2.0.0dev,>=1.22.2, but you have google-api-core 2.10.0 which is incompatible.\n",
            "google-api-python-client 1.12.8 requires google-api-core<2dev,>=1.21.0, but you have google-api-core 2.10.0 which is incompatible.\n",
            "tfx-bsl 1.2.0 requires absl-py<0.13,>=0.9, but you have absl-py 1.3.0 which is incompatible.\n",
            "tfx-bsl 1.2.0 requires google-cloud-bigquery<2.21,>=1.28.0, but you have google-cloud-bigquery 2.34.4 which is incompatible.\n",
            "tfx-bsl 1.2.0 requires numpy<1.20,>=1.16, but you have numpy 1.21.6 which is incompatible.\n",
            "tfx-bsl 1.2.0 requires tensorflow-metadata<1.3,>=1.2, but you have tensorflow-metadata 1.12.0 which is incompatible.\n",
            "tensorflow-data-validation 1.2.0 requires absl-py<0.13,>=0.9, but you have absl-py 1.3.0 which is incompatible.\n",
            "tensorflow-data-validation 1.2.0 requires google-cloud-bigquery<2.21,>=1.28.0, but you have google-cloud-bigquery 2.34.4 which is incompatible.\n",
            "tensorflow-data-validation 1.2.0 requires numpy<1.20,>=1.16, but you have numpy 1.21.6 which is incompatible.\n",
            "tensorflow-data-validation 1.2.0 requires tensorflow-metadata<1.3,>=1.2, but you have tensorflow-metadata 1.12.0 which is incompatible.\n",
            "google-cloud-build 3.10.0 requires google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0, but you have google-api-core 2.10.0 which is incompatible.\u001b[0m\u001b[31m\n",
            "\u001b[0mSuccessfully installed google-api-core-2.10.0 protobuf-3.20.3\n"
          ]
        }
      ],
      "source": [
        "! pip3 install --upgrade  google-cloud-aiplatform \\\n",
        "                          google-cloud-bigquery \\\n",
        "                          google-api-core==2.10"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "id": "79b78466-0488-4991-9cea-48e2f59eecd4",
      "metadata": {
        "id": "63ab4c042de1"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "google-api-core==2.10.0\n"
          ]
        }
      ],
      "source": [
        "! pip3 freeze | grep google-api-core"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "id": "def9983e-9571-4697-b511-23022027eccc",
      "metadata": {
        "id": "ad48b6a2d6bc"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: google-cloud-aiplatform in /home/jupyter/.local/lib/python3.7/site-packages (1.20.0)\n",
            "Requirement already satisfied: google-cloud-storage<3.0.0dev,>=1.32.0 in /home/jupyter/.local/lib/python3.7/site-packages (from google-cloud-aiplatform) (1.44.0)\n",
            "Requirement already satisfied: google-cloud-resource-manager<3.0.0dev,>=1.3.3 in /opt/conda/lib/python3.7/site-packages (from google-cloud-aiplatform) (1.6.0)\n",
            "Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0 in /opt/conda/lib/python3.7/site-packages (from google-cloud-aiplatform) (2.10.0)\n",
            "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /opt/conda/lib/python3.7/site-packages (from google-cloud-aiplatform) (3.20.3)\n",
            "Requirement already satisfied: google-cloud-bigquery<3.0.0dev,>=1.15.0 in /opt/conda/lib/python3.7/site-packages (from google-cloud-aiplatform) (2.34.4)\n",
            "Requirement already satisfied: packaging<22.0.0dev,>=14.3 in /opt/conda/lib/python3.7/site-packages (from google-cloud-aiplatform) (21.3)\n",
            "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.0 in /home/jupyter/.local/lib/python3.7/site-packages (from google-cloud-aiplatform) (1.22.1)\n",
            "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (2.28.1)\n",
            "Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (2.15.0)\n",
            "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /home/jupyter/.local/lib/python3.7/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.56.4)\n",
            "Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /home/jupyter/.local/lib/python3.7/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.50.0)\n",
            "Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in /home/jupyter/.local/lib/python3.7/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.34.1)\n",
            "Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.4.1 in /opt/conda/lib/python3.7/site-packages (from google-cloud-bigquery<3.0.0dev,>=1.15.0->google-cloud-aiplatform) (2.3.2)\n",
            "Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from google-cloud-bigquery<3.0.0dev,>=1.15.0->google-cloud-aiplatform) (1.3.3)\n",
            "Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /opt/conda/lib/python3.7/site-packages (from google-cloud-bigquery<3.0.0dev,>=1.15.0->google-cloud-aiplatform) (2.8.2)\n",
            "Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in /opt/conda/lib/python3.7/site-packages (from google-cloud-resource-manager<3.0.0dev,>=1.3.3->google-cloud-aiplatform) (0.12.4)\n",
            "Requirement already satisfied: six in /home/jupyter/.local/lib/python3.7/site-packages (from google-cloud-storage<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.15.0)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/jupyter/.local/lib/python3.7/site-packages (from packaging<22.0.0dev,>=14.3->google-cloud-aiplatform) (2.4.7)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (0.2.7)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (4.9)\n",
            "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/jupyter/.local/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (4.2.4)\n",
            "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /opt/conda/lib/python3.7/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<3.0.0dev,>=1.15.0->google-cloud-aiplatform) (1.1.2)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (2022.9.14)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.26.11)\n",
            "Requirement already satisfied: charset-normalizer<3,>=2 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (2.1.0)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (3.3)\n",
            "Requirement already satisfied: cffi>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<3.0.0dev,>=1.15.0->google-cloud-aiplatform) (1.15.1)\n",
            "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (0.4.8)\n",
            "Requirement already satisfied: pycparser in /opt/conda/lib/python3.7/site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<3.0.0dev,>=1.15.0->google-cloud-aiplatform) (2.21)\n"
          ]
        }
      ],
      "source": [
        "! pip3 install --upgrade  google-cloud-aiplatform "
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "id": "991bd096-b28e-4c52-b24d-5b9a8445f482",
      "metadata": {
        "id": "6f5f019d2230"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "google-api-core==2.10.0\n"
          ]
        }
      ],
      "source": [
        "! pip3 freeze | grep google-api-core"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "id": "8e99b0d0-75b5-41de-a967-17e8fc5255f2",
      "metadata": {
        "id": "96bb7856a8c6"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: tensorflow-data-validation in /opt/conda/lib/python3.7/site-packages (1.2.0)\n",
            "Collecting tensorflow-data-validation\n",
            "  Downloading tensorflow_data_validation-1.12.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (18.2 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m18.2/18.2 MB\u001b[0m \u001b[31m29.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: six<2,>=1.12 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow-data-validation) (1.15.0)\n",
            "Requirement already satisfied: tensorflow-metadata<1.13,>=1.12.0 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow-data-validation) (1.12.0)\n",
            "Requirement already satisfied: absl-py<2.0.0,>=0.9 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow-data-validation) (1.3.0)\n",
            "Requirement already satisfied: apache-beam[gcp]<3,>=2.40 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow-data-validation) (2.41.0)\n",
            "Requirement already satisfied: tensorflow<3,>=2.11 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow-data-validation) (2.11.0)\n",
            "Requirement already satisfied: pyfarmhash<0.4,>=0.2 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow-data-validation) (0.3.2)\n",
            "Collecting tfx-bsl<1.13,>=1.12.0\n",
            "  Downloading tfx_bsl-1.12.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (21.6 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m21.6/21.6 MB\u001b[0m \u001b[31m48.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
            "\u001b[?25hCollecting pyarrow<7,>=6\n",
            "  Using cached pyarrow-6.0.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25.6 MB)\n",
            "Requirement already satisfied: numpy<2,>=1.16 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow-data-validation) (1.21.6)\n",
            "Requirement already satisfied: pandas<2,>=1.0 in /opt/conda/lib/python3.7/site-packages (from tensorflow-data-validation) (1.3.5)\n",
            "Requirement already satisfied: protobuf<4,>=3.13 in /opt/conda/lib/python3.7/site-packages (from tensorflow-data-validation) (3.20.3)\n",
            "Collecting joblib>=1.2.0\n",
            "  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)\n",
            "Requirement already satisfied: proto-plus<2,>=1.7.1 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.22.1)\n",
            "Requirement already satisfied: httplib2<0.21.0,>=0.8 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.19.1)\n",
            "Requirement already satisfied: python-dateutil<3,>=2.8.0 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.8.2)\n",
            "Requirement already satisfied: crcmod<2.0,>=1.7 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.7)\n",
            "Requirement already satisfied: cloudpickle<3,>=2.1.0 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.1.0)\n",
            "Requirement already satisfied: dill<0.3.2,>=0.3.1.1 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.3.1.1)\n",
            "Requirement already satisfied: pydot<2,>=1.2.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.4.2)\n",
            "Requirement already satisfied: pytz>=2018.3 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2022.1)\n",
            "Requirement already satisfied: hdfs<3.0.0,>=2.1.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.7.0)\n",
            "Requirement already satisfied: fastavro<2,>=0.23.6 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.6.1)\n",
            "Requirement already satisfied: requests<3.0.0,>=2.24.0 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.28.1)\n",
            "Requirement already satisfied: orjson<4.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (3.8.0)\n",
            "Requirement already satisfied: typing-extensions>=3.7.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (3.7.4.3)\n",
            "Requirement already satisfied: grpcio<2,>=1.33.1 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.50.0)\n",
            "Requirement already satisfied: pymongo<4.0.0,>=3.8.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (3.12.3)\n",
            "Requirement already satisfied: google-cloud-recommendations-ai<0.8.0,>=0.1.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.2.0)\n",
            "Requirement already satisfied: google-cloud-language<2,>=1.3.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.3.2)\n",
            "Requirement already satisfied: google-cloud-bigquery<3,>=1.6.0 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.34.4)\n",
            "Requirement already satisfied: google-apitools<0.5.32,>=0.5.31 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.5.31)\n",
            "Requirement already satisfied: google-cloud-bigquery-storage<2.14,>=2.6.3 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.13.2)\n",
            "Requirement already satisfied: google-cloud-core<3,>=0.28.1 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.3.2)\n",
            "Requirement already satisfied: grpcio-gcp<1,>=0.2.2 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.2.2)\n",
            "Requirement already satisfied: cachetools<5,>=3.1.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (4.2.4)\n",
            "Requirement already satisfied: google-auth-httplib2<0.2.0,>=0.1.0 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.1.0)\n",
            "Requirement already satisfied: google-api-core!=2.8.2,<3 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.10.0)\n",
            "Requirement already satisfied: google-cloud-pubsublite<2,>=1.2.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.4.2)\n",
            "Requirement already satisfied: google-cloud-dlp<4,>=3.0.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (3.9.2)\n",
            "Requirement already satisfied: google-cloud-datastore<2,>=1.8.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.15.5)\n",
            "Requirement already satisfied: google-cloud-spanner<2,>=1.13.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.19.3)\n",
            "Requirement already satisfied: google-auth<3,>=1.18.0 in /opt/conda/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.15.0)\n",
            "Requirement already satisfied: google-cloud-bigtable<2,>=0.31.1 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.7.2)\n",
            "Requirement already satisfied: google-cloud-videointelligence<2,>=1.8.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.16.3)\n",
            "Requirement already satisfied: google-cloud-pubsub<3,>=2.1.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.6.0)\n",
            "Requirement already satisfied: google-cloud-vision<2,>=0.38.0 in /home/jupyter/.local/lib/python3.7/site-packages (from apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.0.2)\n",
            "Collecting protobuf<4,>=3.13\n",
            "  Using cached protobuf-3.19.6-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)\n",
            "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (0.4.0)\n",
            "Requirement already satisfied: wrapt>=1.11.0 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (1.12.1)\n",
            "Requirement already satisfied: h5py>=2.9.0 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (3.1.0)\n",
            "Requirement already satisfied: flatbuffers>=2.0 in /opt/conda/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (2.0.7)\n",
            "Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (59.8.0)\n",
            "Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (2.11.0)\n",
            "Requirement already satisfied: tensorboard<2.12,>=2.11 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (2.11.0)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (1.1.0)\n",
            "Requirement already satisfied: astunparse>=1.6.0 in /opt/conda/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (1.6.3)\n",
            "Requirement already satisfied: libclang>=13.0.0 in /opt/conda/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (14.0.6)\n",
            "Requirement already satisfied: keras<2.12,>=2.11.0 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (2.11.0)\n",
            "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (0.27.0)\n",
            "Requirement already satisfied: opt-einsum>=2.3.2 in /opt/conda/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (3.3.0)\n",
            "Requirement already satisfied: google-pasta>=0.1.1 in /opt/conda/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (0.2.0)\n",
            "Requirement already satisfied: packaging in /opt/conda/lib/python3.7/site-packages (from tensorflow<3,>=2.11->tensorflow-data-validation) (21.3)\n",
            "Requirement already satisfied: googleapis-common-protos<2,>=1.52.0 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorflow-metadata<1.13,>=1.12.0->tensorflow-data-validation) (1.56.4)\n",
            "Collecting tensorflow-serving-api!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,<3,>=1.15\n",
            "  Using cached tensorflow_serving_api-2.11.0-py2.py3-none-any.whl (37 kB)\n",
            "Requirement already satisfied: google-api-python-client<2,>=1.7.11 in /home/jupyter/.local/lib/python3.7/site-packages (from tfx-bsl<1.13,>=1.12.0->tensorflow-data-validation) (1.12.8)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.7/site-packages (from astunparse>=1.6.0->tensorflow<3,>=2.11->tensorflow-data-validation) (0.37.1)\n",
            "Collecting google-api-core!=2.8.2,<3\n",
            "  Using cached google_api_core-2.11.0-py3-none-any.whl (120 kB)\n",
            "Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /home/jupyter/.local/lib/python3.7/site-packages (from google-api-python-client<2,>=1.7.11->tfx-bsl<1.13,>=1.12.0->tensorflow-data-validation) (3.0.1)\n",
            "  Downloading google_api_core-1.34.0-py3-none-any.whl (120 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m120.2/120.2 kB\u001b[0m \u001b[31m18.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: fasteners>=0.14 in /home/jupyter/.local/lib/python3.7/site-packages (from google-apitools<0.5.32,>=0.5.31->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.18)\n",
            "Requirement already satisfied: oauth2client>=1.4.12 in /home/jupyter/.local/lib/python3.7/site-packages (from google-apitools<0.5.32,>=0.5.31->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (4.1.3)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (4.9)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.2.7)\n",
            "Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.3.3)\n",
            "Requirement already satisfied: grpc-google-iam-v1<0.13dev,>=0.12.3 in /opt/conda/lib/python3.7/site-packages (from google-cloud-bigtable<2,>=0.31.1->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.12.4)\n",
            "Requirement already satisfied: libcst>=0.3.10 in /home/jupyter/.local/lib/python3.7/site-packages (from google-cloud-pubsub<3,>=2.1.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.4.7)\n",
            "Requirement already satisfied: overrides<7.0.0,>=6.0.1 in /home/jupyter/.local/lib/python3.7/site-packages (from google-cloud-pubsublite<2,>=1.2.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (6.2.0)\n",
            "Requirement already satisfied: grpcio-status>=1.18.0 in /home/jupyter/.local/lib/python3.7/site-packages (from google-cloud-pubsublite<2,>=1.2.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.34.1)\n",
            "Requirement already satisfied: cached-property in /home/jupyter/.local/lib/python3.7/site-packages (from h5py>=2.9.0->tensorflow<3,>=2.11->tensorflow-data-validation) (1.5.2)\n",
            "Requirement already satisfied: docopt in /home/jupyter/.local/lib/python3.7/site-packages (from hdfs<3.0.0,>=2.1.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.6.2)\n",
            "Requirement already satisfied: pyparsing<3,>=2.4.2 in /home/jupyter/.local/lib/python3.7/site-packages (from httplib2<0.21.0,>=0.8->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.4.7)\n",
            "Requirement already satisfied: charset-normalizer<3,>=2 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.1.0)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (3.3)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.26.11)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2022.9.14)\n",
            "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/jupyter/.local/lib/python3.7/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (0.4.6)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.7/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (3.4.1)\n",
            "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (0.6.1)\n",
            "Requirement already satisfied: werkzeug>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (2.2.2)\n",
            "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /opt/conda/lib/python3.7/site-packages (from tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (1.8.1)\n",
            "Collecting google-api-core[grpc,grpcgcp]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5\n",
            "  Using cached google_api_core-2.10.2-py3-none-any.whl (115 kB)\n",
            "  Using cached google_api_core-2.10.1-py3-none-any.whl (115 kB)\n",
            "  Using cached google_api_core-2.9.0-py3-none-any.whl (115 kB)\n",
            "  Using cached google_api_core-2.8.2-py3-none-any.whl (114 kB)\n",
            "\u001b[33mWARNING: google-api-core 2.8.2 does not provide the extra 'grpcgcp'\u001b[0m\u001b[33m\n",
            "\u001b[0m  Using cached google_api_core-2.8.1-py3-none-any.whl (114 kB)\n",
            "  Using cached google_api_core-2.8.0-py3-none-any.whl (114 kB)\n",
            "  Using cached google_api_core-2.7.3-py3-none-any.whl (114 kB)\n",
            "  Using cached google_api_core-2.7.2-py3-none-any.whl (114 kB)\n",
            "  Using cached google_api_core-2.7.1-py3-none-any.whl (114 kB)\n",
            "  Using cached google_api_core-2.7.0-py3-none-any.whl (114 kB)\n",
            "  Using cached google_api_core-2.6.1-py3-none-any.whl (114 kB)\n",
            "  Using cached google_api_core-2.6.0-py2.py3-none-any.whl (114 kB)\n",
            "  Using cached google_api_core-2.5.0-py2.py3-none-any.whl (111 kB)\n",
            "  Using cached google_api_core-2.4.0-py2.py3-none-any.whl (111 kB)\n",
            "  Using cached google_api_core-2.3.2-py2.py3-none-any.whl (109 kB)\n",
            "Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (1.3.1)\n",
            "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /opt/conda/lib/python3.7/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.1.2)\n",
            "Requirement already satisfied: pyyaml>=5.2 in /home/jupyter/.local/lib/python3.7/site-packages (from libcst>=0.3.10->google-cloud-pubsub<3,>=2.1.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (5.4.1)\n",
            "Requirement already satisfied: typing-inspect>=0.4.0 in /home/jupyter/.local/lib/python3.7/site-packages (from libcst>=0.3.10->google-cloud-pubsub<3,>=2.1.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.8.0)\n",
            "Requirement already satisfied: importlib-metadata>=4.4 in /opt/conda/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (4.12.0)\n",
            "Requirement already satisfied: pyasn1>=0.1.7 in /opt/conda/lib/python3.7/site-packages (from oauth2client>=1.4.12->google-apitools<0.5.32,>=0.5.31->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.4.8)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in /opt/conda/lib/python3.7/site-packages (from werkzeug>=1.0.1->tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (2.1.1)\n",
            "Requirement already satisfied: cffi>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (1.15.1)\n",
            "Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (3.8.1)\n",
            "Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow<3,>=2.11->tensorflow-data-validation) (3.2.0)\n",
            "Requirement already satisfied: mypy-extensions>=0.3.0 in /opt/conda/lib/python3.7/site-packages (from typing-inspect>=0.4.0->libcst>=0.3.10->google-cloud-pubsub<3,>=2.1.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (0.4.3)\n",
            "Requirement already satisfied: pycparser in /opt/conda/lib/python3.7/site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]<3,>=2.40->tensorflow-data-validation) (2.21)\n",
            "Installing collected packages: pyarrow, protobuf, joblib, google-api-core, tensorflow-serving-api, tfx-bsl, tensorflow-data-validation\n",
            "  Attempting uninstall: pyarrow\n",
            "    Found existing installation: pyarrow 2.0.0\n",
            "    Uninstalling pyarrow-2.0.0:\n",
            "      Successfully uninstalled pyarrow-2.0.0\n",
            "  Attempting uninstall: protobuf\n",
            "    Found existing installation: protobuf 3.20.3\n",
            "    Uninstalling protobuf-3.20.3:\n",
            "      Successfully uninstalled protobuf-3.20.3\n",
            "  Attempting uninstall: joblib\n",
            "    Found existing installation: joblib 0.14.1\n",
            "    Uninstalling joblib-0.14.1:\n",
            "      Successfully uninstalled joblib-0.14.1\n",
            "  Attempting uninstall: google-api-core\n",
            "    Found existing installation: google-api-core 2.10.0\n",
            "    Uninstalling google-api-core-2.10.0:\n",
            "      Successfully uninstalled google-api-core-2.10.0\n",
            "  Attempting uninstall: tensorflow-serving-api\n",
            "    Found existing installation: tensorflow-serving-api 2.7.4\n",
            "    Uninstalling tensorflow-serving-api-2.7.4:\n",
            "      Successfully uninstalled tensorflow-serving-api-2.7.4\n",
            "  Attempting uninstall: tfx-bsl\n",
            "    Found existing installation: tfx-bsl 1.2.0\n",
            "    Uninstalling tfx-bsl-1.2.0:\n",
            "      Successfully uninstalled tfx-bsl-1.2.0\n",
            "  Attempting uninstall: tensorflow-data-validation\n",
            "    Found existing installation: tensorflow-data-validation 1.2.0\n",
            "    Uninstalling tensorflow-data-validation-1.2.0:\n",
            "      Successfully uninstalled tensorflow-data-validation-1.2.0\n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "tensorflow-transform 1.2.0 requires absl-py<0.13,>=0.9, but you have absl-py 1.3.0 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires google-cloud-bigquery<2.21,>=1.28.0, but you have google-cloud-bigquery 2.34.4 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires numpy<1.20,>=1.16, but you have numpy 1.21.6 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires pyarrow<3,>=1, but you have pyarrow 6.0.1 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<2.6,>=1.15.2, but you have tensorflow 2.11.0 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires tensorflow-metadata<1.3.0,>=1.2.0, but you have tensorflow-metadata 1.12.0 which is incompatible.\n",
            "tensorflow-transform 1.2.0 requires tfx-bsl<1.3.0,>=1.2.0, but you have tfx-bsl 1.12.0 which is incompatible.\n",
            "tensorflow-io 0.18.0 requires tensorflow<2.6.0,>=2.5.0, but you have tensorflow 2.11.0 which is incompatible.\n",
            "tensorflow-io 0.18.0 requires tensorflow-io-gcs-filesystem==0.18.0, but you have tensorflow-io-gcs-filesystem 0.27.0 which is incompatible.\n",
            "kfp 1.8.14 requires google-auth<2,>=1.6.1, but you have google-auth 2.15.0 which is incompatible.\n",
            "google-vizier 0.0.4 requires absl-py<1.0,>=0.7, but you have absl-py 1.3.0 which is incompatible.\n",
            "google-vizier 0.0.4 requires googleapis-common-protos==1.56.0, but you have googleapis-common-protos 1.56.4 which is incompatible.\n",
            "google-vizier 0.0.4 requires grpcio<=1.47.0,>=1.35.0, but you have grpcio 1.50.0 which is incompatible.\n",
            "google-vizier 0.0.4 requires numpy==1.21.5, but you have numpy 1.21.6 which is incompatible.\n",
            "pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.2.0 which is incompatible.\u001b[0m\u001b[31m\n",
            "\u001b[0mSuccessfully installed google-api-core-2.8.1 joblib-1.2.0 protobuf-3.20.1 pyarrow-6.0.1 tensorflow-data-validation-1.12.0 tensorflow-serving-api-2.11.0 tfx-bsl-1.12.0\n"
          ]
        }
      ],
      "source": [
        "!pip3 install --upgrade tensorflow-data-validation"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 8,
      "id": "ad6a3712-993c-47e4-9592-a9804ca5c904",
      "metadata": {
        "id": "970a7cf43846"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "google-api-core @ file:///home/conda/feedstock_root/build_artifacts/google-api-core-split_1653881570487/work\n"
          ]
        }
      ],
      "source": [
        "! pip3 freeze | grep google-api-core"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "name": "Untitled.ipynb",
      "toc_visible": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
